version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi-network

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - fastapi-network
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:567234@db:5432/hw02"

networks:
  fastapi-network:

volumes:
  postgres_data:
